{
  pkgs,
  ...
}:
{
  imports = [
    ./keyd.nix
    ./secret.nix
    ./powerprofile.nix
    ./calendar.nix
    ./tailscale.nix
    ./vpn.nix
  ];

  services.upower.enable = true;

  # Configure keymap in X11
  services.xserver.xkb = {
    layout = "dk";
    # variant = "nodeadkeys";
  };

  services.displayManager.sddm = {
    enable = true;
    wayland.enable = true;
    package = pkgs.kdePackages.sddm;
  };

  # services.fprintd = {
  #   enable = true;
  #   package = pkgs.fprintd-tod;
  #   tod.enable = true;
  #   # Search for "libfprint" in packages to find other drivers
  #   tod.driver = pkgs.libfprint-2-tod1-elan;
  # };

  services.scx = {
    enable = true;
    scheduler = "scx_bpfland";
    package = pkgs.scx.rustscheds;
  };

  services.udisks2.enable = true;
  services.gvfs.enable = true;

  services.flatpak.enable = true;


  # environment.etc."resolv.conf".text = ''
  #   # Generated by environment.etc (NixOS static DNS fix)
  #   nameserver 127.0.0.1
  #   nameserver ::1
  #   # Trust the AD (authentic data) flag and use EDNS(0)
  #   options trust-ad edns0
  # '';

  # environment.etc."resolv.conf" = {
  #   mode = "0644";
  #   text = "nameserver ::1";
  # };
}
